---
language: python
python: '2.7'
sudo: false
branches:
  only:
    - master
    - stable
addons:
  apt:
    sources:
      - python-apt
      - python-pycurl

matrix:
  allow_failures:
    - env: PIP_ANSIBLE_VERSION='>=2.0'
  fast_finish: true

env:
  global:
    - secure: "Clwb4YNDY/OQoKjcOcGJmgEF3zmGOXKz+9jTbuudK7za1nrS2ocXlT1k4LSqH936Wx2kJPtB+Z4HtdNQ8bxO9T3V5c54zqrwvZtdemzQccSt/ZlCCeDqoukek9Rc/X5BVV00bDCgpk2MwWtJY9X22e+3yvUtCRHEvMeJ96pDXzPv5JKqRKfKNZ8mLsUvHhyFci7vlmFCyUyM32zc4WA2zgZGiL/ouXW353j9qgIsqseBhuWgz4cHuPYWW8WamclKm1+KkaP/4AMsAO98fUwh8YupE4GxqcyjImtRloxesxIH79Z3dR5Ye3uVO+DSpNeYuMr1rN/WzzHJBX4DdNAM/a54sNhgaViHdZhGSL2GBI1M2/iEu1EmBYLiISh4kK/NGzoAiEh4mN65CndMcciJt3bok+65vh8BQuXN/aptGsUsZ3iNs9AEn8bFDIsmcd7eLgBeinzzBhCPBvrLMtxWpdc8QNcg7XeFpzdQ5GRGTLlaKp2+FVbEny1hg5B+3CnumxsEblMNZscJUKDnO5N/vIGMnHtjgwjV8lZNoKBFGiAdtlzZXrpJi4xWLzfdp7sY3hTl/JM05c35JaB0mHgP68Ne5opbqrm+vQbma9guBLXyNejZT6MSJnlWn7VEpy18LN6zLNGYsx7yg7Hpws4wjH0Z286atQGVkDTQ1GGEMgg="
    - secure: "GX2Ad/uKOSy0URx9kPYchGKVY3+fhlN48B/bhBNMFD+hDXuZ3zakO116gdlfO/ZpvHFnayVOPaFe/qJoANGviZYvZSx9PtApghJcMLb6Kyh+95mdC4ow1Q9tjbjE11PRJ74yE0KlQ8rPJTA9d9VZGA+1a2ilM3kgI9AFukl3r4BY9AxmPxCdRSnIfNqei/8YNI4Oiktgr8lqlWkPj4b7bD96msgAlYZUbAf+0Ovnm1COadt2WqldFWAcieFeTCZ9IWuLfXtOlHILZq8MkMPuiEJ7o9ecItQ+1WvG7LSRakLoYozFm1sjOciY8D8wtPkPqiQCOm8SdyHfG6RXWUd1A2+ZOUjjBU0T/Xymm1enDmzhyRXNlbB+uaw0efu4fEM9jOcA4atplrSUPoVXdqbLi+Rz3fQP76Sclx+EQfo0dlQg08SxINUPvemk81BQLl9tMzQWwOIdbHxULZochlz1wqpvAQYKaxd4s9XO96fFvSyZsNe6Q3RrXOU2ebgB9BRtszMFGgml35Z1KOPL6vQ/GJbEDaAFVz+kbIFxhICJnr+OKDcmeIsASR5+QBOJeUwOqFKxIAdBEla8580PfD9ONmbPbI7spyhQQrUKJignMHzgDcbpK7Rbt4MdHNfvzezG4UpdNs6gevXfzt9agqAoln+ityVYVAsS5zYkEMi9pWA="
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local
      PAGERDUTY_MAINTENANCE_WINDOW_START: '2016-12-02T14:00:00Z'
      PAGERDUTY_MAINTENANCE_WINDOW_END: '2016-12-02T15:00:00Z'

  matrix:
    - PIP_ANSIBLE_VERSION: "'>=1.9,<2.0'"
    - PIP_ANSIBLE_VERSION: "'>=2.0'"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install --pre "ansible $PIP_ANSIBLE_VERSION"
script:
  - ansible-playbook --version
  - ansible-playbook --syntax-check -i test/inventory test/playbook.yml
  - ansible-playbook  -i test/inventory -l travis test/playbook.yml --connection=local -vvvv
...
