---
- name: Because we need to create valid JSON and then pass it in later we create a file cache locally
  template:
    src: 'json.j2'
    dest: "/Users/bhanlon/Workspace/Work/inviqa/ansible-pagerduty-maintenance-window/cache/{{ [item.0, item.1] | join('') | hash }}"
  register: pagerduty_maintenance_window_cache
  with_subelements:
    - pagerduty_maintenance_windows
    - dates

- name: Read in vars
  debug:
    msg: " {{ lookup('file', item.path )}} "
  with_items: pagerduty_maintenance_window_cache.results




...
